### ISSUE TITLE
Error: not implemented

### ISSUE THREAD

**Issue by vkfont** [wallabyjs/atom-wallaby#20]
Hello.

Im getting strange error on this line: https://github.com/vkfont/gstreamer/blob/wallaby-err/test/stream.coffee#L22 (everything is fine with `npm test`)

Environment:
- mac os
- node v0.12.7 installed via nvm
- coffeescript
- wallaby: Atom plugin v1.0.12, Core v1.0.130
- config: https://github.com/vkfont/gstreamer/blob/wallaby-err/wallaby.js

Error screenshot: http://pasteboard.co/1mxaHCgd.png

Anyone have an idea? Thank you.

**Comment by ArtemGovorov** [comment]
It passes in mocha because mocha doesn't wait for the error and its process is killed once tests are finished, while wallaby reuses node workers so it has a chance to catch the error.

I have simplified the error path and here is one liner causing the issue:
`new (require 'stream').Readable().on 'data', ->`

A test like this one:
``` CoffeeScript
  it 'create stream', ->
    new (require 'stream').Readable().on 'data', ->
```
will report no errors in mocha, but the mentioned error in wallaby.

If you give mocha some time, it will also catch it. For example this one:
``` CoffeeScript
  it 'create stream', (done) ->
    new (require 'stream').Readable().on 'data', ->
    setTimeout done, 1000
```
will be failing both in mocha and wallaby.

Perhaps you may change your test setup so it doesn't throw the error?

**Comment by ArtemGovorov** [comment]
Here is the [one way to fix it](http://stackoverflow.com/questions/22422968/excepetion-in-data-event-handler-binding-on-read-stream), by adding `_read` noop function to your `remoteStream` in the test file.

**Comment by vkfont** [comment]
thank you for your reply, now its much clearer :+1:
