### ISSUE TITLE
Improve switching single-user license between computers

### ISSUE THREAD

**Issue by jiku** [wallabyjs/atom-wallaby#27]
I'm trying to use my single-user license on my lap- instead of desktop and get

```
Wallaby.js is stopped because your license is being used elsewhere on the network by .... Only one active computer at the same time may use the license.

If you would like to purchase an additional license, please visit our website. If you have already purchased the license, please activate it.
```

even though I disabled the package on the desktop.
What's the easiest way to switch between them? Would be great if it just worked by stopping Wallaby on the other computer.

**Comment by ArtemGovorov** [comment]
> Would be great if it just worked by stopping Wallaby on the other computer.

It should actually work like this. I think the issue is wallaby.js core process is still hanging somewhere on your desktop (perhaps because of the editor crash or something like that). Please try to kill all node processes on your desktop (or just restart) and it should work no problem for you on your laptop.

Please let me know if it helps.
