### ISSUE TITLE
Frustrating to "trial" wallaby

### ISSUE THREAD

**Issue by ctrlplusb** [wallabyjs/atom-wallaby#29]
Hi;

Wallaby is looking like a really exciting project.  I was hoping to evaluate it before getting any purchase orders rolling out.  

I managed to install it okay and got it configured towards our toolset.  All good from there, but when starting up Wallaby I get notified that I am in a trial mode, no problem on this but the popup appears every time I run it.  More annoying than this though is that my Wallaby session seems to time out very quickly.  I assuming this is because I am currently running it in trial mode.  

All of this is severely impacting my experience with your product, and is frankly putting me off.  However, I have such high hopes for Wallaby I decided that I would reach out to explain my frustrations as a potential customer.

It would be super awesome if you could change the rules around the trial period to not be so notification verbose and to allow full usage up to a future date.  Allowing us to gain a proper feel for your product and how it would operate in "fully licensed mode" would, in my opinion, allow confidence to grow in your product and result in sales.

Pleeaaaaasssee make this happen.

Let me know if I am being a douche and have completely misconfigured Wallaby, however, my experience thus far is the above.

Thanks

**Comment by ctrlplusb** [comment]
Argh, I couldn't take it and ended up buying a licence!

It's soooo awesome!  Love the product.

Please address my concerns above though.  The session timeouts are really annoying.  I am pinging some big guns in your guys favour.

**Comment by ArtemGovorov** [comment]
Thanks for your feedback and for the order Sean!

As mentioned on [our website](http://wallabyjs.com/), we do offer longer trial period without activation prompts for anyone who's interested. Just send us an email to wallabyjs@gmail.com and I'll arrange an extended trial license key for your team.

We'll also consider you suggestion about having less 'noisy' default trial mode and will have a look what we can about it.

**Comment by smeijer** [comment]
The trial is indeed frustrating. It's very short in time, and not well documented. The website says you can download a trial, but does not explain clearly how long this trial is going to last. Emailing to extend the trial feels like to much work. And even than, it's not clear for what time range you're going to extend it.

I've read somewhere in google-groups that it's a trial-license for 2 weeks, with possible extension for 1 week.

The product is awesome. I'm sure more people will buy when they have a little better use of the trial.

I'm even willing to register an account to get a key that's valid for lets say a month. After that lock it until I have paid.

I am convinced of the power of wallaby, and I'm seriously considering to buy it. But because of the current stage of my project I was not able to test wallaby to its full extend.

My advise; make it clear on the website for what time-range this trial license is valid. So people can plan, and try it when they really have the time available.

**Comment by ArtemGovorov** [comment]
@smeijer 
Thanks for your feedback!

I have added a better explanation of the trial period on our website.

The trial period is 1 month. During the trial period, you will have to occasionally restart your editor (to get another trial session, which is about 1 hour long). Before it happens, there's a notification explaining why wallaby will stop and what to do to continue the trial. 

Emailing us is only required if you'd get a license key that would allow to work without those restarts (just like fully licensed wallaby would do). Hopefully it's not much harder than to register some sort of account and addresses your concern. Either way, please send me an email to wallabyjs@gmail.com and I'll send you the key for a longer trial period without activation prompts.

**Comment by ArtemGovorov** [comment]
@smeijer Regarding the time range for the trial extension - we are pretty flexible in terms of extending trial periods on individual case basis. Just let us know your needs, and we'll sort it out for you.

**Comment by joshsten** [comment]
I'd like to echo similar trial frustrations. The trial cut offs in the middle of working are so frustrating.  It's very off-putting. It makes it harder to recommend to colleagues, because the initial experience has so much annoyance.

Don't get me wrong, the software seems awesome! I just wish the trial experience wasn't so frustrating. I'd like to suggest making the "occasional" restart much less occasional.

**Comment by ArtemGovorov** [comment]
@joshsten Thanks for your feedback. We'll tweak some params of the trial limitation to make it better. 

Also as mentioned above, we offer painless trial without any restrictions upon request. Please send us an email to hello@wallabyjs.com and we'll arrange trial period for you and your team without activation prompts and restarts.

**Comment by amitagrawal11** [comment]
@ArtemGovorov, I agree with all of them above. its too much frustrating to install wallaby in VS Code, even no such document is provided online to get it installed correctly for specific language. 

I tried it for Angular 4+ project, ANgular CLI in VS Code editor but it did not work for me :(. 

As per my understanding with licenses, each company now a days provide trial for about a month so that user could explore it better and can set their mind whether purchasing license would be beneficiary or not.

As far as I have gone through your website, it looks interesting for me and wanted to explore before purchasing it.

Please provide me documentation as well as trial license.

**Comment by ArtemGovorov** [comment]
@amitagrawal11 We do have [online documentation](https://wallabyjs.com/docs/). If you open the [Angular docs section](https://wallabyjs.com/docs/integration/angular.html), the first link you'll find there is the [sample repo of Angular CLI generated projects with instructions on how to setup Wallaby for it](https://github.com/wallabyjs/ngCliWebpackSample#wallabyjs). Also, as you are using VS Code, you may find [this tutorial useful](https://wallabyjs.com/docs/intro/get-started-vscode.html).

If you prefer a video tutorials, here is the [video on how to setup Wallaby with Angular 4+ project, Angular CLI in VS Code editor](https://www.youtube.com/watch?v=VQwZ7ULHdXA).

> as well as trial license

As mentioned above, we offer painless trial without any restrictions upon request. Please send us an email to hello@wallabyjs.com and we'll arrange trial period for you and your team without activation prompts and restarts.
