### ISSUE TITLE
Wallaby stopped reporting spec line numbers on failures

### ISSUE THREAD

**Issue by aaronjensen** [wallabyjs/atom-wallaby#6]
I think this used to work, it still works when I run via karma:

![cid-travel_booking-site - atom 2015-09-01 11-22-36](https://cloud.githubusercontent.com/assets/8588/9612668/cc69e458-509b-11e5-8db5-520cc35338ff.png)

```
 EventContainer
    when the event errors
       renders not found
          PhantomJS 1.9.8 (Mac OS X 0.0.0)
             12) AssertionError: expected to have a child with name 'NotFoundd' and props: {"event":{"error":"sadface"}}
                at childWithName (/Users/aaronjensen/aaa/specs/index.js:69408 <- webpack:///specs/support/shallow/chaiAssertions.js:19:0)
                at /Users/aaronjensen/aaa/specs/index.js:66785 <- webpack:///specs/components/eventContainer.spec.js:61:0

```

**Comment by ArtemGovorov** [comment]
It looks like it works with all chai assertions, including customs ones, except properties: `Assertion.addProperty('...', function () { // ...`. The issue with custom properties is that they are added via defineProperty + getter and PhantomJs cuts the error stack when it's raised from within the property.

I have tried it with karma and getting the same issue as in wallaby. Are you sure you've tried the exact same thing in both wallaby and karma? If it does work for you in karma, could you please share a small sample repo with your karma and wallaby configs, If I can make the same thing work in karma (in PhantomJs), I'll just use the same trick in wallaby to make it work.

**Comment by ArtemGovorov** [comment]
BTW, are you webpack-ing/`require`-ing chai from your karma tests or loading it globally via some karma chai plugin? Do you do the in wallaby config?

**Comment by aaronjensen** [comment]
The plot thickens... it seems to be a problem w/ specs only in our specs/components directory. 

here's a repro: https://github.com/aaronjensen/wallaby-line-number-repro

for chai, we're using karma plugins to load it, so for wallaby we're loading it similarly in wallaby.conf. Is there a preferred way to do it?

**Comment by ArtemGovorov** [comment]
Thanks heaps for the repo, interesting issue indeed.

It turns out it's the [default way mocha works](https://github.com/mochajs/mocha/issues/1859), it filters out stack lines with `components` substrings in it.

It works in karma because when you're using webpack plugin, it bundles your code into a single `base/specs/index.js` file, so when the error is raised, the stack only contains `base/specs/index.js:line_num` entires, no `components`, so mocha doesn't touch the stack and later on source map plugin producing the `<- webpack:///specs/components/notworking.spec.js:3:0` mapping.

Wallaby doesn't bundle everything into one file to leverage browser caching and avoid serving the large file over and over, so the raised error stack contains `components` and the line gets filtered out by mocha. In fact, if you don't use webpack you'd hit the same issue with karma.

There are a few options to resolve the issue.

One way is to call mocha `fullTrace` to suppress stack filtering:

``` JavaScript
    bootstrap: function(w) {
      var mocha = w.testFramework;
      mocha.fullTrace();
      window.expect = chai.expect;
      window.__moduleBundler.loadTests();
    }
```

That'll also include chai stack entries. Possibly there's a way to monkey patch mocha right in the bootstrap function to avoid filtering out lines with `components`, but I haven't found one.

Another way is to remove `testFramework: 'mocha',` from your config file (or replace it with `testFramework: 'jasmine`). It'll use `jasmine` by default and everything will still work because you're using describe/it style API that they both support identically and chai assertions that work no matter where. Nothing else has to change - you may still use mocha to run your tests from karma, etc. The only thing that you may need to do differently in this case is to [use testing framework specific way to run individual tests/specs](https://github.com/wallabyjs/public/issues/224), if you're using these features of a test runner.

> for wallaby we're loading it similarly in wallaby.conf. Is there a preferred way to do it?

The way you do it is the fastest way. You may also `require` chai as you're using webpack, works for those who prefer to avoid having any global dependencies and like to `require` everything. I prefer to have it loaded the way you do it.

Feel free to close the issue if you're happy with any of the proposed solutions.

**Comment by aaronjensen** [comment]
Ok, interesting. That definitely seems like a problem given the tendency to name folders `components` with react. I'll give jasmine a shot along w/

```js
      context = describe;
      context.only = fdescribe;
      it.only = fit;
      describe.only = fdescribe;
```

as a shim :) Thanks for digging in, hopefully they fix this on mocha.

**Comment by aaronjensen** [comment]
Even better, here's a working monkey patch:

```js
      var fail = Mocha.Runner.prototype.fail;
      var originalFilter = Mocha.utils.stackTraceFilter();

      function stackFilter(stack) {
        return originalFilter(stack.replace("/components/", "/__componentz__/"))
          .replace("/__componentz__/", "/components/");
      }

      Mocha.Runner.prototype.fail = function(test, err) {
        if (err.stack) {
          err.stack = stackFilter(err.stack);
        }

        return fail.apply(this, [test, err]);
      }
      mocha.fullTrace();
```

**Comment by ArtemGovorov** [comment]
@aaronjensen Awesome! I have been looking into `mocha` for a way to monkey patch it, but didn't know `Mocha` was exported into window as well.
